In [ ]:
import pandas as pd

df = pd.read_csv("naukri_com-job_sample.csv")

df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              21996 non-null  object
 1   education            20004 non-null  object
 2   experience           21996 non-null  object
 3   industry             21995 non-null  object
 4   jobdescription       21996 non-null  object
 5   jobid                22000 non-null  int64
 6   joblocation_address  21499 non-null  object
 7   jobtitle             22000 non-null  object
 8   numberofpositions    4464 non-null   float64
 9   payrate              21903 non-null  object
 10  postdate             21977 non-null  object
 11  site_name            3987 non-null   object
 12  skills               21472 non-null  object
 13  uniq_id              22000 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.3+ MB

In [ ]:
df.isnull().sum()

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [ ]:
df = df.drop(columns=[
    "site_name",
    "numberofpositions",
    "uniq_id",
    "jobid"
])

In [ ]:
df.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'joblocation_address', 'jobtitle', 'payrate', 'postdate', 'skills'],
      dtype='object')

In [ ]:
df["joblocation_address"] = df["joblocation_address"].str.split(",").str[0]
df["joblocation_address"] = df["joblocation_address"].str.replace("Bengaluru/Bangalore", "Bengaluru")
df["joblocation_address"] = df["joblocation_address"].str.strip()

df.rename(columns={"joblocation_address": "City"}, inplace=True)

df["City"].value_counts().head()

City
Bengaluru                   7935
Mumbai                      3660
Chennai                     1726
Hyderabad / Secunderabad    1504
Delhi                       1470
Name: count, dtype: int64

In [ ]:
def extract_experience(exp):
    try:
        exp = exp.replace(" yrs", "")
        low, high = exp.split(" - ")
        return (int(low) + int(high)) / 2
    except:
        return None

df["Experience_Years"] = df["experience"].apply(extract_experience)

df.drop(columns=["experience"], inplace=True)

df["Experience_Years"].head()

0     0.5
1     0.0
2     6.0
3    13.0
4     7.0
Name: Experience_Years, dtype: float64

In [ ]:
df = df[~df["payrate"].str.contains("Not Disclosed", na=False)]

In [ ]:
import re

def extract_salary(s):
    try:
        numbers = re.findall(r'\d+', s.replace(",", ""))
        if len(numbers) >= 2:
            low = int(numbers[0])
            high = int(numbers[1])
            return (low + high) / 2
        else:
            return None
    except:
        return None

df["Average_Salary"] = df["payrate"].apply(extract_salary)

df.drop(columns=["payrate"], inplace=True)

df["Average_Salary"].head()

0     187500.0
1     200000.0
6     475000.0
8     150000.0
12    212500.0
Name: Average_Salary, dtype: float64

In [ ]:
df["Posting_Date"] = pd.to_datetime(df["Posting_Date"])

In [ ]:
df["Year"] = df["Posting_Date"].dt.year
df["Month"] = df["Posting_Date"].dt.month
df["Month_Name"] = df["Posting_Date"].dt.month_name()

In [ ]:
df.columns

Index(['company', 'education', 'industry', 'jobdescription', 'City',
       'jobtitle', 'Posting_Date', 'skills', 'Experience_Years',
       'Average_Salary', 'Year', 'Month', 'Month_Name'],
      dtype='object')

In [ ]:
df = df.rename(columns={
    "industry": "Industry",
    "skills": "Skill_Category",
    "jobtitle": "Job_Title"
})

In [ ]:
df.columns

Index(['company', 'education', 'Industry', 'jobdescription', 'City',
       'Job_Title', 'Posting_Date', 'Skill_Category', 'Experience_Years',
       'Average_Salary', 'Year', 'Month', 'Month_Name'],
      dtype='object')

In [ ]:
df = df.dropna(subset=[
    "City",
    "Average_Salary",
    "Experience_Years",
    "Industry",
    "Skill_Category"
])

In [ ]:
df = df[(df["Average_Salary"] > 50000) & (df["Average_Salary"] < 5000000)]

In [ ]:
df.shape

(4473, 13)

In [ ]:
df.to_csv("job_market_dashboard_ready.csv", index=False)

In [ ]:
from google.colab import files
files.download("job_market_dashboard_ready.csv")

In [ ]:
df["education"] = df["education"].fillna("Not Specified")

In [ ]:
df["education"].isnull().sum()

np.int64(0)

In [ ]:
df.to_csv("job_market_dashboard.csv", index=False)

In [ ]:
from google.colab import files
files.download("job_market_dashboard.csv")